### ISSUE TITLE
Not compatible with 32-bit version of Windows (or six4 idk my toaster is broken cant write six)

### ISSUE THREAD

**Issue by SKevo18** [Thomas-QM/rANdomcAP#1]
title

**Comment by canislupaster** [comment]
oh noes

**Comment by canislupaster** [comment]
oh nose

**Comment by canislupaster** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by canislupaster** [comment]
[random_cap.zip](https://github.com/Thomas-QM/rANdomcAP/files/3095866/random_cap.zip)
I dUNno IF it WorKS On 32 bit MacHINes It DOesNT woRK on My 64BIt mAChinE GO aND tRY haVE a GOOd DAY mR KOStuM  kAT a UkaKAKaaAAaaAAAaaAAaaAAaa
